#! /bin/sh
# xrandr --output LVDS1 --mode 1440x900

feh --bg-scale ~/Pictures/Wallpapers/wave.png

killall polybar
polybar -r --config=.config/polybar/config.ini main &

pgrep -x sxhkd > /dev/null || sxhkd &
# picom -b
# alacritty &
# dunst &
killall unclutter
unclutter --ignore-scrolling &


libinput-gestures-setup start


killall nm-applet
nm-applet &
killall blueman-applet
blueman-applet &
killall pcloud
pcloud &

setxkbmap -option caps:swapescape

# Bspwm

bspc monitor -d I II III IV V
bspc config border_width        3
bspc config window_gap			5

bspc config pointer_mod         mod4
bspc config pointer_action1     move
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 29
# Colors
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"

bspc config split_ratio          0.50
bspc config focus_follows_pointer true

bspc rule -a "*" state=tiled
bspc rule -a "Desktop — Plasma" state=floating
bspc rule -a "krunner" state=floating
bspc rule -a "plasmashell" state=floating
bspc rule -a "Plasma" state=floating
bspc rule -a "plasma-desktop" state=floating
bspc rule -a "Kmix" state=floating
