#! /bin/sh
# xrandr --output LVDS1 --mode 1440x900

feh --bg-scale /home/invidiae/Pictures/Wallpapers/Image.jpeg

# killall polybar
polybar -r --config=.config/polybar/config.ini main &

pgrep -x sxhkd > /dev/null || sxhkd &

picom -b
alacritty &
# dunst &

unclutter --ignore-scrolling &

killall pcloud
pcloud &

# nm-applet &
setxkbmap -option caps:swapescape

# Bspwm

bspc monitor -d I II III IV V #VI VII VIII IX X
bspc config border_width        5
bspc config window_gap			5

bspc config pointer_mod         mod4
bspc config pointer_action1     move

# Colors
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"

bspc config split_ratio          0.50
bspc config focus_follows_pointer true

bspc rule -a "*" state=tiled
